package Modelo;
// Generated 06-dic-2018 10:03:00 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Telefonos generated by hbm2java
 */
public class Telefonos  implements java.io.Serializable {


     private String idcliente;
     private String telCasa;
     private String telTrabajo;
     private String telCelular;
     private Set<Cliente> clientes = new HashSet<Cliente>(0);

    public Telefonos() {
    }

	
    public Telefonos(String idcliente) {
        this.idcliente = idcliente;
    }
    public Telefonos(String idcliente, String telCasa, String telTrabajo, String telCelular, Set<Cliente> clientes) {
       this.idcliente = idcliente;
       this.telCasa = telCasa;
       this.telTrabajo = telTrabajo;
       this.telCelular = telCelular;
       this.clientes = clientes;
    }

    public Telefonos(String idcliente, String telCasa, String telTrabajo, String telCelular) {
        this.idcliente = idcliente;
        this.telCasa = telCasa;
        this.telTrabajo = telTrabajo;
        this.telCelular = telCelular;
    }
   
    
    public String getIdcliente() {
        return this.idcliente;
    }
    
    public void setIdcliente(String idcliente) {
        this.idcliente = idcliente;
    }
    public String getTelCasa() {
        return this.telCasa;
    }
    
    public void setTelCasa(String telCasa) {
        this.telCasa = telCasa;
    }
    public String getTelTrabajo() {
        return this.telTrabajo;
    }
    
    public void setTelTrabajo(String telTrabajo) {
        this.telTrabajo = telTrabajo;
    }
    public String getTelCelular() {
        return this.telCelular;
    }
    
    public void setTelCelular(String telCelular) {
        this.telCelular = telCelular;
    }
    public Set<Cliente> getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set<Cliente> clientes) {
        this.clientes = clientes;
    }




}


