package Modelo;
// Generated 06-dic-2018 13:08:09 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cobertura generated by hbm2java
 */
public class Cobertura  implements java.io.Serializable {


     private int idcobertura;
     private String nombre;
     private Set<Poliza> polizas = new HashSet<Poliza>(0);
     private Set<DescripcionCobertura> descripcionCoberturas = new HashSet<DescripcionCobertura>(0);
     private Set<Servicio> servicios = new HashSet<Servicio>(0);

    public Cobertura() {
    }

	
    public Cobertura(int idcobertura) {
        this.idcobertura = idcobertura;
    }
    public Cobertura(int idcobertura, String nombre, Set<Poliza> polizas, Set<DescripcionCobertura> descripcionCoberturas, Set<Servicio> servicios) {
       this.idcobertura = idcobertura;
       this.nombre = nombre;
       this.polizas = polizas;
       this.descripcionCoberturas = descripcionCoberturas;
       this.servicios = servicios;
    }
   
    public int getIdcobertura() {
        return this.idcobertura;
    }
    
    public void setIdcobertura(int idcobertura) {
        this.idcobertura = idcobertura;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Poliza> getPolizas() {
        return this.polizas;
    }
    
    public void setPolizas(Set<Poliza> polizas) {
        this.polizas = polizas;
    }
    public Set<DescripcionCobertura> getDescripcionCoberturas() {
        return this.descripcionCoberturas;
    }
    
    public void setDescripcionCoberturas(Set<DescripcionCobertura> descripcionCoberturas) {
        this.descripcionCoberturas = descripcionCoberturas;
    }
    public Set<Servicio> getServicios() {
        return this.servicios;
    }
    
    public void setServicios(Set<Servicio> servicios) {
        this.servicios = servicios;
    }




}


