package Modelo;
// Generated 06-dic-2018 13:08:09 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Contacto generated by hbm2java
 */
public class Contacto  implements java.io.Serializable {


     private int idcontacto;
     private String nombre;
     private Set<Servicio> servicios = new HashSet<Servicio>(0);

    public Contacto() {
    }

	
    public Contacto(int idcontacto) {
        this.idcontacto = idcontacto;
    }
    public Contacto(int idcontacto, String nombre, Set<Servicio> servicios) {
       this.idcontacto = idcontacto;
       this.nombre = nombre;
       this.servicios = servicios;
    }
   
    public int getIdcontacto() {
        return this.idcontacto;
    }
    
    public void setIdcontacto(int idcontacto) {
        this.idcontacto = idcontacto;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Servicio> getServicios() {
        return this.servicios;
    }
    
    public void setServicios(Set<Servicio> servicios) {
        this.servicios = servicios;
    }




}


