package Modelo;
// Generated 06-dic-2018 13:08:09 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Credenciales generated by hbm2java
 */
public class Credenciales  implements java.io.Serializable {


     private int idcredenciales;
     private String correo;
     private String contrasena;
     private Set<Clientes> clienteses = new HashSet<Clientes>(0);

    public Credenciales() {
    }

	
    public Credenciales(int idcredenciales, String correo, String contrasena) {
        this.idcredenciales = idcredenciales;
        this.correo = correo;
        this.contrasena = contrasena;
    }
    public Credenciales(int idcredenciales, String correo, String contrasena, Set<Clientes> clienteses) {
       this.idcredenciales = idcredenciales;
       this.correo = correo;
       this.contrasena = contrasena;
       this.clienteses = clienteses;
    }
   
    public int getIdcredenciales() {
        return this.idcredenciales;
    }
    
    public void setIdcredenciales(int idcredenciales) {
        this.idcredenciales = idcredenciales;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public Set<Clientes> getClienteses() {
        return this.clienteses;
    }
    
    public void setClienteses(Set<Clientes> clienteses) {
        this.clienteses = clienteses;
    }




}


