package Modelo;
// Generated 06-dic-2018 13:08:09 by Hibernate Tools 4.3.1



/**
 * DescripcionCobertura generated by hbm2java
 */
public class DescripcionCobertura  implements java.io.Serializable {


     private int iddescripcionCobertura;
     private Cobertura cobertura;

    public DescripcionCobertura() {
    }

    public DescripcionCobertura(int iddescripcionCobertura, Cobertura cobertura) {
       this.iddescripcionCobertura = iddescripcionCobertura;
       this.cobertura = cobertura;
    }
   
    public int getIddescripcionCobertura() {
        return this.iddescripcionCobertura;
    }
    
    public void setIddescripcionCobertura(int iddescripcionCobertura) {
        this.iddescripcionCobertura = iddescripcionCobertura;
    }
    public Cobertura getCobertura() {
        return this.cobertura;
    }
    
    public void setCobertura(Cobertura cobertura) {
        this.cobertura = cobertura;
    }




}


