package Modelo;
// Generated 06-dic-2018 13:08:09 by Hibernate Tools 4.3.1



/**
 * DescripcionServicio generated by hbm2java
 */
public class DescripcionServicio  implements java.io.Serializable {


     private int iddescripcionServicio;
     private Servicio servicio;

    public DescripcionServicio() {
    }

    public DescripcionServicio(int iddescripcionServicio, Servicio servicio) {
       this.iddescripcionServicio = iddescripcionServicio;
       this.servicio = servicio;
    }
   
    public int getIddescripcionServicio() {
        return this.iddescripcionServicio;
    }
    
    public void setIddescripcionServicio(int iddescripcionServicio) {
        this.iddescripcionServicio = iddescripcionServicio;
    }
    public Servicio getServicio() {
        return this.servicio;
    }
    
    public void setServicio(Servicio servicio) {
        this.servicio = servicio;
    }




}


