package Modelo;
// Generated 06-dic-2018 13:08:09 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Servicio generated by hbm2java
 */
public class Servicio  implements java.io.Serializable {


     private int idservicio;
     private String nombre;
     private Set<Contacto> contactos = new HashSet<Contacto>(0);
     private Set<DescripcionServicio> descripcionServicios = new HashSet<DescripcionServicio>(0);
     private Set<Cobertura> coberturas = new HashSet<Cobertura>(0);

    public Servicio() {
    }

	
    public Servicio(int idservicio) {
        this.idservicio = idservicio;
    }
    public Servicio(int idservicio, String nombre, Set<Contacto> contactos, Set<DescripcionServicio> descripcionServicios, Set<Cobertura> coberturas) {
       this.idservicio = idservicio;
       this.nombre = nombre;
       this.contactos = contactos;
       this.descripcionServicios = descripcionServicios;
       this.coberturas = coberturas;
    }
   
    public int getIdservicio() {
        return this.idservicio;
    }
    
    public void setIdservicio(int idservicio) {
        this.idservicio = idservicio;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Contacto> getContactos() {
        return this.contactos;
    }
    
    public void setContactos(Set<Contacto> contactos) {
        this.contactos = contactos;
    }
    public Set<DescripcionServicio> getDescripcionServicios() {
        return this.descripcionServicios;
    }
    
    public void setDescripcionServicios(Set<DescripcionServicio> descripcionServicios) {
        this.descripcionServicios = descripcionServicios;
    }
    public Set<Cobertura> getCoberturas() {
        return this.coberturas;
    }
    
    public void setCoberturas(Set<Cobertura> coberturas) {
        this.coberturas = coberturas;
    }




}


