package Modelo;
// Generated 06-dic-2018 13:08:09 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoUsuario generated by hbm2java
 */
public class TipoUsuario  implements java.io.Serializable {


     private int idtipoUsuario;
     private String nombre;
     private Set<Clientes> clienteses = new HashSet<Clientes>(0);
	
    public TipoUsuario(String nombre) {
        this.nombre = nombre;
    }
    public TipoUsuario(int idtipoUsuario, String nombre, Set<Clientes> clienteses) {
       this.idtipoUsuario = idtipoUsuario;
       this.nombre = nombre;
       this.clienteses = clienteses;
    }
   
    public int getIdtipoUsuario() {
        return this.idtipoUsuario;
    }
    
    public void setIdtipoUsuario(int idtipoUsuario) {
        this.idtipoUsuario = idtipoUsuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Clientes> getClienteses() {
        return this.clienteses;
    }
    
    public void setClienteses(Set<Clientes> clienteses) {
        this.clienteses = clienteses;
    }




}


