version: '3'
services:
  database:
    image: mysql:latest
    # volumes:
    #   - ../database/database.sql:/docker-entrypoint-initdb.d/0_init.sql
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=multi_asistencia
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - "3307:3306"