package Modelo;
// Generated 02-dic-2018 13:44:00 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Telefono generated by hbm2java
 */
public class Telefono  implements java.io.Serializable {


     private int id;
     private Integer numero;
     private Set personas = new HashSet(0);

    public Telefono() {
    }

	
    public Telefono(int id) {
        this.id = id;
    }
    public Telefono(int id, Integer numero, Set personas) {
       this.id = id;
       this.numero = numero;
       this.personas = personas;
    }
    //este metodo no es creado por el hibernate, un constructor pero sin el Set personas

    public Telefono(int id, Integer numero) {
        this.id = id;
        this.numero = numero;
    }
    
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getNumero() {
        return this.numero;
    }
    
    public void setNumero(Integer numero) {
        this.numero = numero;
    }
    public Set getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set personas) {
        this.personas = personas;
    }




}


